id: 80b1dc514de54cf1802c666b4b2a948a
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_152-The_Questions_of_Sagaramati-v2
  language: en
  author: ''
  volume: {}
